[package]
name = "reia"
version = "0.1.0"
authors = ["Wisha Wa <wisha.wa@yandex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.74"

[dependencies.js-sys]
version = "0.3.51"

[dependencies.web-sys]
version = "0.3.51"
features = [
	'Document',
	'Element',
	'DomTokenList',
	'Window',
	'Node',
	'Text',
	'HtmlElement',
	'HtmlDivElement',
	'HtmlButtonElement',
	'console',
]

[workspace]
members = [
	"examples/minimal_counter/",
	"examples/playground/"
]